#!/usr/bin/env python3
"""Shared style metadata and generated-index helpers."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STYLES_DIR = ROOT / "styles"
README_PATH = ROOT / "README.md"
INDEX_PATH = STYLES_DIR / "index.yaml"
BEGIN_MARKER = "<!-- BEGIN GENERATED STYLE INDEX -->"
END_MARKER = "<!-- END GENERATED STYLE INDEX -->"


class StyleError(ValueError):
    pass


@dataclass(frozen=True)
class Style:
    id: str
    name: str
    description: str
    best_for: tuple[str, ...]
    avoid_for: tuple[str, ...]
    external_assets: str
    directory: Path


def parse_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---(?:\n|$)", text, re.DOTALL)
    if not match:
        raise StyleError(f"{path}: missing YAML frontmatter")

    result: dict[str, object] = {}
    for line_number, raw in enumerate(match.group(1).splitlines(), start=2):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise StyleError(f"{path}:{line_number}: expected key: value")
        key, value = (part.strip() for part in line.split(":", 1))
        if not value:
            raise StyleError(f"{path}:{line_number}: empty values are not supported")
        if value.startswith("[") or value.startswith('"'):
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError as exc:
                raise StyleError(f"{path}:{line_number}: invalid JSON-style value") from exc
        elif value.isdigit():
            parsed = int(value)
        else:
            parsed = value
        result[key] = parsed
    return result


def load_styles(root: Path = ROOT) -> list[Style]:
    styles_dir = root / "styles"
    styles: list[Style] = []
    for directory in sorted(path for path in styles_dir.iterdir() if path.is_dir()):
        guide = directory / "design-language.md"
        if not guide.exists():
            continue
        data = parse_frontmatter(guide)
        required = {"schema_version", "id", "name", "description", "best_for", "avoid_for", "external_assets"}
        missing = sorted(required - data.keys())
        if missing:
            raise StyleError(f"{guide}: missing fields: {', '.join(missing)}")
        if data["schema_version"] != 1:
            raise StyleError(f"{guide}: unsupported schema_version {data['schema_version']!r}")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", directory.name):
            raise StyleError(f"{guide}: style directory must be lowercase kebab-case")
        if data["id"] != directory.name:
            raise StyleError(f"{guide}: id must match directory name {directory.name!r}")
        if not isinstance(data["best_for"], list) or not data["best_for"]:
            raise StyleError(f"{guide}: best_for must be a non-empty JSON-style list")
        if not isinstance(data["avoid_for"], list):
            raise StyleError(f"{guide}: avoid_for must be a JSON-style list")
        if data["external_assets"] not in {"none", "optional", "required"}:
            raise StyleError(f"{guide}: external_assets must be none, optional, or required")
        styles.append(
            Style(
                id=str(data["id"]),
                name=str(data["name"]),
                description=str(data["description"]),
                best_for=tuple(str(item) for item in data["best_for"]),
                avoid_for=tuple(str(item) for item in data["avoid_for"]),
                external_assets=str(data["external_assets"]),
                directory=directory,
            )
        )
    if not styles:
        raise StyleError(f"{styles_dir}: no styles found")
    names = [style.name.casefold() for style in styles]
    if len(names) != len(set(names)):
        raise StyleError(f"{styles_dir}: style names must be unique")
    return styles


def render_index(styles: list[Style]) -> str:
    lines = ["# Generated by scripts/build_index.py. Do not edit by hand.", "schema_version: 1", "styles:"]
    for style in styles:
        lines.extend(
            [
                f"  {style.id}:",
                f"    name: {json.dumps(style.name, ensure_ascii=False)}",
                f"    description: {json.dumps(style.description, ensure_ascii=False)}",
                f"    best_for: {json.dumps(list(style.best_for), ensure_ascii=False)}",
                f"    avoid_for: {json.dumps(list(style.avoid_for), ensure_ascii=False)}",
                f"    external_assets: {style.external_assets}",
            ]
        )
    return "\n".join(lines) + "\n"


def render_readme_table(styles: list[Style]) -> str:
    lines = [BEGIN_MARKER, "| Style | Best for | Description |", "|---|---|---|"]
    for style in styles:
        name = style.name.replace("|", "\\|")
        description = style.description.replace("|", "\\|")
        best_for = ", ".join(style.best_for).replace("|", "\\|")
        lines.append(
            f"| [{name}](styles/{style.id}/) | {best_for} | {description} |"
        )
    lines.append(END_MARKER)
    return "\n".join(lines)


def replace_readme_table(readme: str, table: str) -> str:
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(readme):
        raise StyleError(f"{README_PATH}: generated style-index markers are missing")
    return pattern.sub(table, readme)
